.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. griffion_qt test_griffion_qt
clean: FORCE
	$(MAKE) -C .. griffion_qt_clean test_griffion_qt_clean
check: FORCE
	$(MAKE) -C .. test_griffion_qt_check
griffion-qt griffion-qt.exe: FORCE
	 $(MAKE) -C .. griffion_qt
apk: FORCE
	$(MAKE) -C .. griffion_qt_apk
